version: '3.8'
services:
  php:
    build: .
    ports:
      - "8080:80"  
    volumes:
      - ./www/trabalho:/var/www/html  
    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=phps
    ports:
      - "8081:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql  
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=phprs
      - MYSQL_DATABASE=phprs
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  dbdata:  
  portainer_data: